language: node_js
node_js:
  - node
script: bash env.sh && npm run test
deploy:
  provider: npm
  email: taylor@helloample.com
  api_key:
    secure: M1tB7DhGxHcSM2phg8eFGO0mFYIL1odN9ZefuRiYRsTEjeYqX+5H5JHEnL8QWDrPwtPufvLG+ElPkdINY4mqzqkZW+UYldt3SHP2nmQZCakTLp3ZFypVDN1RD7emSW+P+XNXJYPwBv0AdzMKl4mLlQWNDXr72fL9e8OTtBvTrjWVnSAudlPNOM9UONGUiKyo3Iu0QqpRLBHvTSCQfcgK2SmkQmV/hjH7RyK5g97jxdgUh21epdR1tysJrGu1F8z3dCenPP29yY/TxSBzZ5hE61rgneJoG8eMEGDs0nbzWL5Yj7Eg+dX+zpHka7L6Lstqv/NKQF3LsUcHXF8SIii1osSqVtnoXPlk/nrCBQEuZeE6EsejONhYVx4NLOoCnIrWgCDitwBfpkvkyGc78FpGXdoZ/IzNlarkl2YozSEZzDPyxlnhBR7xuZKHVeCQ/aXkoCyvsk4BGk/II7JGM09x15d4NvqZsQ+j9ZVhf+/e2zFT7lXg0pJgzfLz1Mw+RdZQxf1DhNb45zLBsR34EO20k8ASR7VIYyJ0Vvg/A0sb3ZzrEZfsfNYz1oA5SkmSIzDhn/m9JZkhv7fiv0S7ZI3pN4dMaZ5X9ctkXj4/veHkz2vjAsm3yay4vP9jfD98nMqCQQVrbBiIgptJB3aAfqlR22PGSA9r87/RZDBlE66lEyU=
  on:
    tags: true
    repo: crdschurch/crds-components
