[build]
  command = '''
    bash env.sh &&
    npm run test &&
    npm run build &&
    npm run storybook:build &&
    cp -R www storybook-static/demo &&
    mv www/build storybook-static &&
    mv dist storybook-static &&
    mv _headers storybook-static
  '''
  functions = "./functions"
  functionsSource="./functions"
